spring:
  application:
    name: activitiesresponses
  config:
    import: optional:configserver:http://osroom-config-server-1:8888
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true

app:
  file-storage:
    url: http://82.29.168.17:8030
