eureka:
  instance:
    hostname: osroom-discovery-1
  client:
    service-url:
      defaultZone: http://osroom-discovery-1:8761/eureka

server:
  port: 8030
spring:
  application:
    name: file-storage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/file-storage
    username: alibou
    password: alibou
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect